## Data analytics--library
**NUMPY---linear algebra,n-dimesional powerful array create by 
adding the small subset of array.**

In [3]:
## array--homogenous datatype
# pip install pandas
import numpy as np

In [145]:
x=[1,2,3,4,5,15,2.56]
type(x)
x

[1, 2, 3, 4, 5, 15, 2.56]

In [23]:
x.append([12,15])
x

[1, 2, 3, 4, 5, 15, 2.56, 12, [12, 15]]

In [147]:
y=np.array(x)
y

array([ 1.  ,  2.  ,  3.  ,  4.  ,  5.  , 15.  ,  2.56])

In [35]:
x=np.array((12,2.5,"kiwi",True))
x.ndim
x

array(['12', '2.5', 'kiwi', 'True'], dtype='<U32')

In [157]:
weight=np.array([54.25,45.63,85.36])
height=np.array([1.63,1.25,1.45])
weight
np.concatenate([weight,height])
np.sum([weight,height],axis=1)

array([185.24,   4.33])

## array methods---

In [163]:
weight=np.array([54.25,45.63,85.36,85])
# shape
weight.shape
type(weight)

numpy.ndarray

In [161]:
weight.size

4

In [165]:
weight.dtype

dtype('float64')

In [80]:
weight.itemsize

8

## creating a array by using inbuilt function


In [179]:
x=np.arange(10,50).reshape(10,4)
x.ndim
x.shape

(10, 4)

In [123]:
## random function--random value but half open interval-(0.0,1.0)

np.random.random((4,5))

array([[0.38782408, 0.78806488, 0.31217087, 0.0308432 , 0.59917464],
       [0.59782523, 0.06347477, 0.00651559, 0.08517335, 0.77253781],
       [0.50377467, 0.95131949, 0.41963387, 0.96401362, 0.34829605],
       [0.25415531, 0.60677056, 0.98890401, 0.91889131, 0.17345945]])

In [187]:
x=np.random.randint(20,60,(50,4))
x

array([[51, 23, 28, 45],
       [57, 26, 47, 20],
       [31, 27, 45, 51],
       [37, 39, 51, 57],
       [57, 46, 57, 51],
       [34, 43, 34, 33],
       [57, 28, 50, 58],
       [42, 50, 38, 44],
       [35, 29, 26, 30],
       [35, 40, 39, 24],
       [38, 44, 52, 56],
       [50, 21, 51, 43],
       [56, 32, 30, 30],
       [48, 51, 52, 45],
       [49, 44, 36, 53],
       [30, 32, 23, 48],
       [34, 21, 44, 24],
       [38, 33, 22, 55],
       [34, 45, 25, 23],
       [22, 42, 41, 39],
       [26, 35, 42, 36],
       [36, 28, 36, 24],
       [48, 50, 46, 40],
       [29, 38, 43, 27],
       [56, 45, 41, 41],
       [31, 48, 46, 31],
       [23, 43, 39, 45],
       [48, 51, 30, 42],
       [44, 55, 26, 22],
       [43, 43, 25, 22],
       [44, 59, 49, 46],
       [55, 23, 35, 27],
       [43, 59, 37, 30],
       [53, 44, 52, 52],
       [42, 23, 29, 25],
       [20, 48, 35, 26],
       [49, 24, 36, 44],
       [51, 23, 56, 43],
       [31, 56, 35, 21],
       [59, 45, 50, 58],


In [201]:
np.random.randn(20)

array([-2.15574397, -0.26506831,  0.53773119, -0.28244582, -0.8489615 ,
       -0.43793007,  1.39700723, -0.01524762, -2.28710781,  0.16569793,
        0.40652616, -0.5254125 , -0.93937208,  0.11077435, -0.45960685,
       -0.96137489, -1.02208103, -0.29651275, -0.56027959,  0.53314553])

In [70]:
import seaborn as sns
x=sns.load_dataset('iris')
x

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

## list and array
1.array takes homogenous element and list take heterogenous element.
2. list take 1 dimensional data but array can take n_dimensional
3.list can take extra memory as compared to array 
4.list can take more time as compared to array
5.The size of the array is fixed where as The size of the lists is variable

In [205]:
x=[25,53.25,75,15,2,25]
for i in x:
    print(i+4)

29
57.25
79
19
6
29


In [209]:
y=np.array(x)
y+4

array([29.  , 57.25, 79.  , 19.  ,  6.  , 29.  ])

In [219]:
lst=range(1,100000)
array=np.arange(1,1000000)

In [221]:
# list execution time
import time 
start_time=time.time()
lst=[i+4 for i in lst]
end_time=time.time()
exectiun_time=end_time-start_time
exectiun_time

0.00799703598022461

In [223]:
# array execution time
import time 
start_time=time.time()
array=array+4
end_time=time.time()
exectiun_time=end_time-start_time
exectiun_time

0.003997802734375

In [236]:
weight=np.array([54.25,45.63,85.36])
height=np.array([[1.63,1.25,1.45]])
np.concatenate([weight,height])
np.power([weight,height],2)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

# slicing and indexing

In [247]:
x=[25,45,36,7,12,25,36,19]
x[3:]

[7, 12, 25, 36, 19]

In [251]:
x=np.arange(1,21).reshape(5,4)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [255]:
x[2,1:3]

array([10, 11])

In [257]:
x[4,3]

20

In [299]:
x[-4:-1,3].shape

(3,)

In [5]:
# AIRTHMATIC OPERATORS
x=np.arange(10,30).reshape(5,4)
y=np.arange(1,21).reshape(5,4)
np.save("my_array.npy",x)

In [323]:
x[0][3]-x[3][2]

-11

In [337]:
x[0]-=2
x

array([[ 6,  7,  8,  9],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29]])

# assignment operator------

In [7]:
import numpy as np
np.load("my_array.npy")

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29]])

In [44]:
x=np.arange(10,30).reshape(4,5)
y=np.arange(1,21).reshape(4,5)
x-=y

In [18]:
x*=2
x

array([[26, 26, 26, 26],
       [26, 26, 26, 26],
       [26, 26, 26, 26],
       [26, 26, 26, 26],
       [26, 26, 26, 26]])

In [24]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [26]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [28]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [73]:
x=np.arange(10,30).reshape(4,5)
y=np.arange(1,21).reshape(5,4)

In [67]:
for i in x:
    if i%2==0:
        print("even")
    else:
        print("odd")
    np.array(i)

odd
even
odd
even
odd
even
odd
even


In [48]:
x @ y

array([[ 580,  640,  700,  760],
       [ 805,  890,  975, 1060],
       [1030, 1140, 1250, 1360],
       [1255, 1390, 1525, 1660]])

In [52]:
x=np.array([1,2,3,4,5,6,7,8])
[i for i in x if i%2==0]

[2, 4, 6, 8]

In [75]:
np.where(x%2==0,x,0)

array([[10,  0, 12,  0, 14],
       [ 0, 16,  0, 18,  0],
       [20,  0, 22,  0, 24],
       [ 0, 26,  0, 28,  0]])

In [ ]:
## higher dimension---stacking

In [79]:
x=np.array([[[2,4],[4,5],[12,15]]])
y=np.array([[[2,4],[4,5],[12,15]]])

In [89]:
x=np.arange(2,12).reshape(5,2)
y=np.random.randint(10,20,(5,2))

In [103]:
np.stack([x,y],axis=2)

array([[[ 2, 19],
        [ 3, 11]],

       [[ 4, 12],
        [ 5, 15]],

       [[ 6, 11],
        [ 7, 18]],

       [[ 8, 11],
        [ 9, 10]],

       [[10, 17],
        [11, 12]]])

In [107]:
np.hstack([x,y])

array([[ 2,  3, 19, 11],
       [ 4,  5, 12, 15],
       [ 6,  7, 11, 18],
       [ 8,  9, 11, 10],
       [10, 11, 17, 12]])